global:
  default-game: Flooder
  min-ready: 5
  min-players: 2
  game-duration: 30
  allow-command: false
  countdown: 10
  allowed-commands: []
  notify-period: 60
  zone-capture-time: 20
  jumps-per-feather: 3
