chest-loot:
- ==: Item
  values:
    chance: .5
  stack:
    ==: org.bukkit.inventory.ItemStack
    type: SPONGE
    # if no amount given, defaults to 0
    damage: 0
    # if no amount given, defaults to 1
    amount: 1
    #meta:
    #  ==: ItemMeta
    #  meta-type: UNSPECIFIC
    #  enchants:
    #    DURABILITY: 3
- ==: Item
  values:
    chance: .5
  stack:
    ==: org.bukkit.inventory.ItemStack
    type: TNT
    # if no amount given, defaults to 0
    damage: 0
    # if no amount given, defaults to 1
    amount: 1
    #meta:
    #  ==: ItemMeta
    #  meta-type: UNSPECIFIC
    #  enchants:
    #    DURABILITY: 3
- ==: Item
  values:
    chance: .5
  stack:
    ==: org.bukkit.inventory.ItemStack
    type: FEATHER
    # if no amount given, defaults to 0
    damage: 0
    # if no amount given, defaults to 1
    amount: 1
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: JumpFeather
    #  enchants:
    #    DURABILITY: 3
- ==: Item
  values:
    chance: .5
  stack:
    ==: org.bukkit.inventory.ItemStack
    type: STICK
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: Knockback Stick
      enchants:
        KNOCKBACK: 1