chest-loot:
- ==: Item
  values:
    chance: .5
  stack:
    ==: org.bukkit.inventory.ItemStack
    type: SPONGE
    # if no amount given, defaults to 0
    damage: 0
    # if no amount given, defaults to 1
    amount: 1
    #meta:
    #  ==: ItemMeta
    #  meta-type: UNSPECIFIC
    #  enchants:
    #    DURABILITY: 3
- ==: FlooderItem
  effectItem: Knockback
  values:
    chance: .5